
version: "3"

services:
  api:
    image: epicenter:dev
    ports:
      - "8000:8000"
    volumes:
      - .:/epicenter/
    networks: ["public", "private"]
    dns: ["8.8.8.8"]
    env_file:
      - .docker/.env
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload"]
    depends_on:
      - "db"
    stdin_open: true
    tty: true

  db:
    image: postgres:11.6-alpine
    restart: unless-stopped
    ports:
      - 5432
    networks: ["private"]
    env_file: .docker/.env
    volumes:
      - .docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "5433:5433"
    links:
      - db:db
    networks: ["private"]
    env_file: .docker/.env
    depends_on: ["db"]
    command:
      [
        "/usr/bin/pgweb",
        "--bind=0.0.0.0",
        "--listen=5433",
        "--url=postgres://epicenter:epicenter@db:5432/epicenter?sslmode=disable",
      ]

networks:
  public:
  private:

volumes:
  postgres-data:
